FROM confluentinc/cp-kafkacat:7.0.14
ARG KAFKA_BROKER_IN=kafka:29092
ARG KAFKA_TOPIC_IN=proto
ARG KAFKA_TOPIC_OUT=json
ARG KAFKA_BROKER_OUT=kafka:29092
ARG PROTO_FILE=test.proto
ENV KAFKA_BROKER_IN $KAFKA_BROKER_IN
ENV KAFKA_TOPIC_IN $KAFKA_TOPIC_IN
ENV KAFKA_BROKER_OUT $KAFKA_BROKER_OUT
ENV KAFKA_TOPIC_OUT $KAFKA_TOPIC_OUT
ENV PROTO_FILE $PROTO_FILE
WORKDIR /app
COPY . /app
ENTRYPOINT kafkacat -b $KAFKA_BROKER_IN -C -t $KAFKA_TOPIC_IN -f '%s--END--' -u -q -o beginning | ./proton json -f ./$PROTO_FILE -m '--END--' | kafkacat -b $KAFKA_BROKER_OUT -P -t $KAFKA_TOPIC_OUT